### ISSUE TITLE
[Bug?]: initial deploy to Vercel not working with latest (rw 7.0.6, node 20)

### ISSUE THREAD

**Issue by jason-curtis** [redwoodjs/redwood#10100]
### What's not working?

Initial deploy to Vercel fails. Error log: https://gist.github.com/jason-curtis/c922f9cf3b5520e9d2d418667555642b

Key section of the log appears to be:
```
[14:27:06.339] $ /vercel/path0/node_modules/.bin/rw data-migrate up
[14:27:07.038] Installing plugin "@redwoodjs/cli-data-migrate"...
[14:27:08.101] error Running this command will add the dependency to the workspace root rather than the workspace itself, which might not be what you want - if you really meant it, make it explicit by running this command again with the -W flag (or --ignore-workspace-root-check).
[14:27:08.101] info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
[14:27:08.116] Error: Command failed with exit code 1: yarn add -D @redwoodjs/cli-data-migrate@7.0.6
```

### How do we reproduce the bug?

* Create a new redwood project w/ `yarn create redwood-app whatever`
* push it to a github repo
* Start a new deploy from that project on Vercel
  * it will fail the first time until you go into project settings and set node version to 20 (expected, I guess?)
* Start a redeploy
* deploy fails with the error above.

### What's your environment? (If it applies)

```shell
(this info may not be relevant since the error is happening on vercel but I ran `yarn rw info` locally)

  System:
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.11.1 - /tmp/xfs-40a4659e/node
    Yarn: 4.1.0 - /tmp/xfs-40a4659e/yarn
  Browsers:
    Chrome: 121.0.6167.139
  npmPackages:
    @redwoodjs/core: 7.0.6 => 7.0.6 
    @redwoodjs/project-config: 7.0.6 => 7.0.6
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by jason-curtis** [comment]
Interestingly, if I deploy manually using a Github Action with these steps it works fine:
```yaml
      - name: Install Vercel CLI
        run: npm install --global vercel@canary
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }} --prod
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --prod
```

But if I use this pre-built GH action, I get the `Running this command will add the dependency to the workspace root` error:
```yaml

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-comment: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Include a --prod flag for Vercel CLI, but leave empty for preview deploys
          vercel-args: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && '--prod' || '' }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}

```
