### ISSUE TITLE
Config: Add redwood.toml setting to disable generating tests and storybook with every generator

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#1166]
Not everyone cares about tests and/or storybook so it's kind of annoying to keep creating the files every time. Let's add config options in `redwood.toml` to stop creating them during generation.

Some folks may also want to generate tests/storybook for only some component types but not others. Maybe you always want them for services, but never for pages. So perhaps there's a global config option as well as per-type config option.

Here are a couple options for syntax:

```toml
# global setting
[generate]
tests = true
storybook = false

# per-side setting
[generate.web]
tests = true
storybook = false
[generate.api]
tests = false

# individual type setting
[generate.services]
tests = true

# more specific settings win (all web-side tests are generated, only services api-side tests are generated)
[generate]
tests = true
[generate.api]
tests = false
[generate.services]
tests = true
```

Another suggestion is just an array of types to generator for. By default, everything is enabled, but as soon as you add the `tests` or `storybook` key then everything becomes disabled except what's included in the array. It seems kind of weird that just the existence of the key causes all tests to be generated or not, so maybe this isn't the most clear option:

```toml
[generate]
tests = ["services", "cells"]
storybook = ["cells"]
```

For now we're talking about defaulting to `true` for the global setting, so existing behavior doesn't change.

Someone also suggested maybe after you've used the generators 3 or 4 times you get an extra notification after the 4th generator saying something like "Did you know you can skip test or storybook generation? See https://redwoodjs.com/docs/redwood.toml"

**Comment by jvanbaarsen** [comment]
I don't see anyone assigned to this, I'd like to take a stab at this.

**Comment by jvanbaarsen** [comment]
@cannikin What do you say about the following syntax :

```toml
[web]
  port = 8910
  apiProxyPath = "/.redwood/functions"
  generateTests = ["services", "components"]
  generateStories = false
[api]
  port = 8911
  schemaPath = "./api/db/schema.prisma"
  generateTests = true
  generateStories = true
[browser]
  open = true
```

So we attach the config to the already existing `side` configs.

**Comment by thedavidprice** [comment]
Fantastic @jvanbaarsen Thank you for jumping in here! I've assigned this to you. 

My two cents on the direction for discussion with you and @cannikin:

## Syntax
The initial suggestions about granularity are likely my fault. I've since redacted and now think it should be simple and either on/off per type of generated file:
```
[generate]
tests = true
storybook = false
```

Given a .toml setting, devs can still specify an option when a specific command is run, which can override the .toml if/when needed. This provides an option to be granular when/if needed.

For now, generated files for both tests and storybook should have a default `true`, which will be set in here in [config.ts](https://github.com/redwoodjs/redwood/blob/main/packages/internal/src/config.ts). We can then use `getConfig` within the generator commands to set the Yargs default, which will either use the config.ts default or the value from a project's .toml. (Make sense?)

## Mock Files
**Q:** Since a mock file can be used by either tests or storybook depending on the case, how should we determine when to (or not to) generate mock files?

## Documentation
1. It's on my list, but the [CLI Documentation](https://redwoodjs.com/docs/cli-commands#generate-alias-g) has yet to be updated with the changes from this related PR https://github.com/redwoodjs/redwood/pull/1454
2. We'll definitely need to update https://redwoodjs.com/docs/app-configuration-redwood-toml
3. Although it's not necessary, should we add the config options to the template .toml file for visibility? 
4. And/or the soon-to-be-released Test Doc by @cannikin?
5. Anywhere else?

> Someone also suggested maybe after you've used the generators 3 or 4 times you get an extra notification after the 4th generator saying something like "Did you know you can skip test or storybook generation? See https://redwoodjs.com/docs/redwood.toml"

^^ This is interesting but might not be worth the work for now. Maybe it's good enough to start with an earlier idea by @cannikin to add this to the Tutorial as a side note.

**Comment by jvanbaarsen** [comment]
@thedavidprice Allright, makes sense!

RE: Mock files:
When adding the CLI flag I made it so that if either a test or a story was present I'd also generate the mock file. This was not something the user has any control over. I'd be in favour of keeping it that way. So if you generate either a story or a test the mock file is included for free.

RE: Documentation
I'll make sure to create a todo list on my PR when submitting with those items. That way we can try and merge all of the things around the same time.

**Comment by thedavidprice** [comment]
Mock Files --> perfect and well done! I hadn't reviewed code or functionality (yet).

Docs --> thank you in advance!

**Comment by mojombo** [comment]
It strikes me that `tests` is generic but `storybook` is specific to a piece of software. I think we should either make them both generic like `tests` and `stories` or specific like `jest` and `storybook`. Curious about all your thoughts on that.

**Comment by jvanbaarsen** [comment]
@mojombo In the CLI I used `stories`. I was planning on doing the same here.

**Comment by cannikin** [comment]
Thanks for the work on this @jvanbaarsen! I agree with @thedavidprice and @mojombo, I like the individual options spelled out:

```toml
[generate]
tests = true
storybook = false
```

Everything else sounds good to me (default to true, generate a mock if generating either a test or a story, etc). On the api side it should create the `scenarios.js` file if it creates the `test.js` file.
