### ISSUE TITLE
[Bug?]: `yarn rw build api` fails when `@redwoodjs/cli` attempts to access `@babel/core`

### ISSUE THREAD

**Issue by tomjdickson** [redwoodjs/redwood#11777]
### What's not working?

Docker node:20-alpine when running `yarn rw build api` we receive the follwing error:

```
Error: @redwoodjs/cli tried to access @babel/core, but it isnt declared in its dependencies; this makes the require call ambiguous and unsound.
#0 1.235
#0 1.235 Required package: @babel/core
#0 1.235 Required by: @redwoodjs/cli@npm:8.4.1 (via /root/.yarn/berry/cache/@redwoodjs-cli-npm-8.4.1-7ff7e7b962-10c0.zip/node_modules/@redwoodjs/cli/dist/lib/)
```

### How do we reproduce the bug?

Using the below Dockerfile.
```Dockerfile
FROM node:20-alpine

# Pass the database URL as an argument
ARG DATABASE_URL

# Install necessary packages
RUN apk update && apk add --no-cache bash git openssh

# Set the working directory
WORKDIR /app

# Copy application files
COPY api api
COPY graphql.config.js .
COPY package.json .
COPY redwood.toml .
COPY yarn.lock .
COPY scripts scripts

# Enable corepack and configure Yarn
RUN corepack enable
RUN yarn set version berry
RUN corepack prepare yarn@stable --activate

# Install dependencies
RUN yarn install

# Run Prisma migrations and generate client
# RUN yarn rw prisma migrate deploy
# RUN yarn rw prisma generate

# Run RedwoodJS data migrations
# RUN npx @redwoodjs/cli-data-migrate

# Build the API
RUN yarn add @redwoodjs/cli@latest
RUN yarn rw build api
RUN echo "yarn rw build api done"

# Remove unnecessary files to minimize image size
RUN rm -rf ./api/src

# Set the working directory for the API
WORKDIR /app/api

# Expose the port for the API
EXPOSE 8911

# Entry point for the application
ENTRYPOINT [ "yarn", "rw", "serve", "api", "--port", "8911" ]
```

and the below Docker Compose

```yml
version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: your_database_url_here # Replace with your actual database URL
    ports:
      - "8911:8911" # Map port 8911 on the host to the container
    environment:
      DATABASE_URL: your_database_url_here # Ensure the container has access to the database URL
    command: yarn rw serve api --port 8911
    volumes:
      - .:/app # Optional: Bind mount the current directory for development purposes
```

### Are you interested in working on this?

- [X] I'm interested in working on this
