### ISSUE TITLE
.ts extension included in serverless.yml setup.

### ISSUE THREAD

**Issue by leetmachine** [redwoodjs/redwood#3217]
issue: `yarn rw setup deploy aws-serverless` includes `.ts` in the config to `serverless.yml`. This causes an error when trying `yarn rw deploy aws` as `Serverless: Configuration warning at 'functions': name 'geocode.ts' must be alphanumeric`.

```
functions:
  geocode.ts:
    description: geocode.ts function deployed on AWS Lambda
    package:
      artifact: api/dist/zipball/geocode.ts.zip # This is the default location of the zip file generated during the deploy command.
    memorySize: 1024 # mb
    timeout: 25 # seconds (max: 29)
    tags: # Tags for this specific lambda function
      endpoint: /.redwood/functions/geocode.ts
    # Uncomment this section to add environment variables either from the Serverless dotenv plugin or using Serverless params
    # environment:
    #   YOUR_FIRST_ENV_VARIABLE: ${env:YOUR_FIRST_ENV_VARIABLE}
    handler: geocode.ts.handler
```
    
  I confirmed that by removing `.ts` in every location I was able to get past the issue.
