### ISSUE TITLE
Add a `scripts/tsconfig.json` to the create-redwood-app template

### ISSUE THREAD

**Issue by realStandal** [redwoodjs/redwood#3733]
Hello,

Making this as an issue in the off-chance there are plans to support something similar in a different way. I have no issue pushing this configuration (or another) up myself.

---

I went to update the `scripts/seed.ts` file that gets generated with a Redwood project and was greeted with a TypeScript error:

<details>
  <summary>TypeScript resolution error</summary>
  
  ![image](https://user-images.githubusercontent.com/25166787/142083693-dfd29c6c-b4d1-4353-9cab-731c949bd912.png)
</details>

The fix is easy enough, here is the `tsconfig.json` file I added to the `scripts/` directory.

<details>
  <summary>scripts/tsconfig.json</summary>
  
```YAML
{
  "compilerOptions": {
    "noEmit": true,
    "allowJs": true,
    "esModuleInterop": true,
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "baseUrl": "./",
    "paths": {
      "api/*": ["../api/*"],
      "web/*": ["../web/*"]
    },
    "typeRoots": ["../node_modules/@types", "./node_modules/@types"],
    "types": ["jest"],
  },
  "include": [
    "./",
    "../.redwood/types/includes/all-*",
  ]
}
```
  
</details>

Was having the `$` character before the resolution something that was desired/necessary? It felt more natural and consistent with each side to leave it off.
