### ISSUE TITLE
yarn rw check should throw

### ISSUE THREAD

**Issue by pi0neerpat** [redwoodjs/redwood#3906]
Currently, `yarn rw check` will only display console.logs for errors. Instead, it should throw, so we can use it properly in a github action

Example error (which does not throw)

```
 api/src/graphql/oauth.sdl.js:8:5: error (SERVICE_NOT_IMPLEMENTED): Service Not Implemented
```

Usage example

```yaml
name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  runCI:
    name: Run CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js v14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache "node_modules"
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: node_modules_${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn rw lint
        shell: bash
      - name: Check
        run: yarn rw check
        shell: bash
```
