### ISSUE TITLE
[deploy: serverless] Configure deployment of redwood web side

### ISSUE THREAD

**Issue by dac09** [redwoodjs/redwood#3986]
## Goal
`yarn rw setup deploy aws-serverless` currently only sets up the deploy of the api side

Setup deploy commands should setup the project so that both api and web sides both can be deployed. 

High level steps should be:
 - `yarn rw build` (includes Web/)
 - configure the apiUrl in `redwood.toml`
```toml
[web]
  port = 8910
  apiUrl = "/api" # 👈 this variable needs to be configured correctly, pointing OR proxying to the deployed host for api functions
```
 - package up the web/dist files 
 - deploy packaged file to s3
 - configure cloudfront to point to the s3 bucket

Key requirements:

- [ ] Ensure page is served through `https`
- [ ] Ensure `apiUrl` is configured correctly OR proxied to the api functions
- [ ] Ensure redirects are setup, so that:
  a) If you go to the root url index.html is served
  b) If you go to some page <rootUrl>/<myPage> and myPage.html doesn't exist, it should return index.html
  c) If you go to some page<rootUrl>/<prerenderedPage> and prerenderedPage.html exists, it should return prerenderedPage.html
