### ISSUE TITLE
Feature Request: Support Deployments to AWS Lambda 

### ISSUE THREAD

**Issue by Jaikant** [redwoodjs/redwood#431]
In continuation to the [forum discussion](https://community.redwoodjs.com/t/deploying-to-aws-lambda/316). Would love to have direct deployments of redwood apps to Lambda and S3. 

What about something like:

`yarn rw deploy aws`   \\ Deploy to lambda and S3 
`yarn rw deploy azure` 
`yarn rw deploy gcp`

Or we could do a generic `yarn rw deploy` which picks the provider config from the `redwood.toml`

Opinions?
On deploying to AWS lambda, we would get an api endpoint. This `api` endpoint would be needed within the `web` part in apollo client for the graphql queries. 

To provide the deployed endpoint to the web part - we could save it into an environment/config variable which is read by the web part (the current implementation picks the config from `redwood.toml` and then uses the webpack define plugin).

The build step would need the `api` to be built first, before the `web`, so the endpoint is known.

**Deploying the API AWS Lambda**

I deployed the redwood `api`, to Lambda successfully. Here are my rough notes, to deploy the `api` side to AWS lambda. It is only a few packaging changes as the zip file generated by[ @netlify/zip-it-and-ship-it](https://github.com/netlify/zip-it-and-ship-it) is not directly deployable to AWS Lambda. 

Go to api/prisma and update schema.prisma with the binary target to be rhel-openssl-1.0.x. 

```
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "rhel-openssl-1.0.x"]
}
```
**Install @netlify/zip-it-ship-it, serverless & serverless-dotenv-plugin**
```
 yarn workspace api add @netlify/zip-it-and-ship-it --dev
 yarn workspace api add serverless --dev
 yarn workspace api add serverless-dotenv-plugin --dev
```

**Build the API**
```
 yarn rw build api
```

** Package it for lambda, using zip-it-ship-it**
```
mkdir zipball
yarn zip-it-and-ship-it api/dist/functions/ zipball/
```

**Changes to zip file generated by zip-it-ship-it**  zip-it-ship-it doesn't package the binary target and schema.prisma file, could be related to this [issue](https://github.com/prisma/prisma/issues/2082) 
```
// Unzip zipball/graphql.zip and move graphQL.js to function directory. So, the import paths for
// graphql.js corrected by

 mkdir dist/functions
 mv graphql.js dist/functions/

// zip-it-ship-it adds the root directory instead of node-modules, 
// lets extract the node-modules from it. copy the node-modules from `Users` into zipball
// On a macbook pro, it is as below. My app name is chat-support
  mv Users/jai/redwood/chat-support/node_modules .

// copy the binary target file into node modules, zip-it-ship-it skips the binary target 
// as well as the schema.prisma file
    cp ../node_modules/@prisma/client/runtime/query-engine-rhel-openssl-1.0.x ./node_modules/@prisma/client/runtime
  cp ../node_modules/@prisma/client/schema.prisma ./node_modules/@prisma/client/

// Lets clean up the directory, before zipping it
rm -rf Users/
// remove the older zip file, graphql.zip
rm graphql.zip

//zip the current directory, which has dist and node-modules
 zip -r graphql.zip .
```

**Using [serverless](https://github.com/serverless/serverless) to deploy, the config serverless.yml, which is at the root of the project.**
```
service: jai-redwood-1
plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-south-1

package:
  artifact: zipball/graphql.zip

functions:
  graphql:
    description: redwood on aws lambda
    memorySize: 1024
    timeout: 30
    handler: dist/functions/graphql.handler
    events:
      - http:
          path: graphql
          method: GET
          cors: true
      - http:
          path: graphql
          method: POST
          cors: true
      - http:
          path: playground
          method: ANY
          cors: true

resources:
  Resources:
```

**Deploy to lambda by:**
```
  yarn serverless deploy -v
```

To make netlify zip-it-and-ship-it work for redwood, we could write a wrapper over it or we could raise an issue with @netlify/zip-it-and-ship-it.  We could also use something like[ serverless-webpack](https://github.com/serverless-heaven/serverless-webpack) to zip it. 

Having a similar deployment to Azure && Google Cloud, could help with an optimal design if any takers?
