### ISSUE TITLE
Add Github Action Labeller to PR's

### ISSUE THREAD

**Issue by Rosenberg96** [redwoodjs/redwood#433]
In the mono repository setting I have personally found it very beneficial to add labels to PR's in order to efficiently filter the affected components of the PR. I see that you are also doing that, which I assume is done manually atm.

Here, I suggest adding the Github Action [Labeler](https://github.com/actions/labeler) to automatically label newly created PR's with meaningful labels. 

Initially, I suggest adding a label matching the component changed in the PR. This can be achieved with a workflow file and a `github/labeler.yml` file.

```
docs:
  - docs/*
  - **/*.md

topic-api:
  - packages/api/*

topic-cli:
  - packages/cli/*

topic-core:
  - packages/core/*
...

```

In addition, a simple workflow should be added `.github/workflows/labeler.yml`

```
name: "Pull Request Labeler"
on:
- pull_request

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
```

I don't know if this is the place to make this suggestion, but if this something you would like I will be happy to open a PR.

EDIT: Unfortunately as mentioned in the repo and in the following [post](https://github.community/t5/GitHub-Actions/Github-Workflow-not-running-from-pull-request-from-forked/td-p/32979) this action is not able on contributions from forked repositories due to security. Hence, it would only run on PR's created by contributors, which is far from ideal and diminishes the upside.
