### ISSUE TITLE
Setting up Security Headers

### ISSUE THREAD

**Issue by jacebenson** [redwoodjs/redwood#4496]
I was trying to shore up the security rating here on observatory.mozilla.org but I can't seem to figure out how to add a bunch of these headers.

It looks like this would be the file I need, but I'm not sure how to set that here.

https://github.com/redwoodjs/redwood/blob/main/packages/create-redwood-app/template/api/server.config.js

Here's the same output I'm getting I want to shore up: https://observatory.mozilla.org/analyze/redwood-playground-auth.netlify.app

**Comment by simoncrypta** [comment]
I feel like it came from the Netlify CDN, and it's not something we can control. I'm maybe wrong ?

**Comment by jacebenson** [comment]
Hmm, maybe I can add the headers this way here on netlify 
https://docs.netlify.com/routing/headers/

**Comment by simoncrypta** [comment]
Oh, that's true ! You can probably add it to this file :
https://github.com/redwoodjs/playground-auth/blob/main/netlify.toml

**Comment by jacebenson** [comment]
yes!  How would I do this on, render?  WOuld that be in the fastify config somehow?

**Comment by simoncrypta** [comment]
Render also use they own static site DNS, they also have a doc to change the headers :
https://render.com/docs/static-site-headers

**Comment by simoncrypta** [comment]
It's can also be set at the render.yaml file 
https://render.com/docs/blueprint-spec
```
  # A static site
  - type: web
    name: my blog
    env: static
    buildCommand: yarn build
    staticPublishPath: ./build
    pullRequestPreviewsEnabled: true # optional
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
    routes:
      - type: redirect
        source: /old
        destination: /new
      - type: rewrite
        source: /a/*
        destination: /a

```
You can find the default template when using `rw setup deploy render` here :
https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/setup/deploy/templates/render.js
