### ISSUE TITLE
Github action fails with yarn 3 since bumping to v0.49.1

### ISSUE THREAD

**Issue by noire-munich** [redwoodjs/redwood#4822]
We've bumped to v0.49.1 today in an attempt to finally get to yarn 3 - super excited.

Locally it runs very well and caused little troubles to upgrade.

The problem occurs when using a github action.

The workflow, truncated:
```
on:
  push:
    branches:
      - preprod

name: Deploy preprod

env:
  repo_name: ***
  node_version: 16.6.1

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: preproduction

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Create environment files
        working-directory: aws
        run: |
          yarn

          # Generate ebextensions env file
          node ./generate_preprod_env.js ebextensions > ./.ebextensions/02-envvars.config

          # Generate dotenv file
          node ./generate_preprod_env.js dotenv > ../.env

// the rest is irrelevant
```

This part has been working well until now, and debugging proves to be rather difficult.

The action fails on step **Create environment files** and unfolding the details only show a diff of a file which should not have been edited outside of our local files. There is no explicit error message:

![image](https://user-images.githubusercontent.com/10271407/159064787-27b77e5c-0b1b-43e8-9ce5-95b8ac5363c0.png)

```
$ yarn rw info
  System:
    OS: Linux 5.13 Ubuntu 21.10 21.10 (Impish Indri)
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.6.1 - /tmp/xfs-a76dd022/node
    Yarn: 3.2.0 - /tmp/xfs-a76dd022/yarn
  Browsers:
    Chrome: 99.0.4844.51
    Firefox: 98.0
  npmPackages:
    @redwoodjs/core: ^0.49.1 => 0.49.1 
    @redwoodjs/eslint-config: ^0.49.1 => 0.49.1 
    @redwoodjs/record: ^0.47.0 => 0.47.1 
```

**Comment by thedavidprice** [comment]
@noire-munich Yarn 3 includes greatly improved resolution than Yarn 1, including more tools to verify and keep yarn.lock robust.

Do take a look at the new (and removed) options for `yarn install` in v3. For CI, you'll see we always run `yarn install --immutable`. Our Smoke Test workflow is a great example to follow in general: 
https://github.com/redwoodjs/redwood/blob/main/.github/workflows/smoke-test.yaml

You should also get in the habit of running `yarn dedup` locally.

To me, this reads like you have a busted yarn.lock. I'd try deleting and rebuilding. And/or start with `yarn dedupe` locally. Definitely use `yarn install --immutable` in CI.

Keep me posted!

**Comment by thedavidprice** [comment]
```
  npmPackages:
    @redwoodjs/core: ^0.49.1 => 0.49.1 
    @redwoodjs/eslint-config: ^0.49.1 => 0.49.1 
    @redwoodjs/record: ^0.47.0 => 0.47.1 
```

Why is Record at a different version? Are all packages at the correct version?

**Comment by virtuoushub** [comment]
Looking at the screenshot, it seems as if the lockfile is using the yarn v1 format.

Agree with @thedavidprice , updating CI to use `yarn install --immutable` explicitly is a good suggestion (it is supposed to default to true on CI, but by setting we remove all doubt). Hopefully that gives more feedback about what is going on.

FWIW in some of my personal projects where I use Yarn 3, I have noticed that dependabot will clobber my yarn v3 formatted lockfile and replace it with a v1 format. This results in the exact same Post-resolution validation errors.

**Comment by noire-munich** [comment]
> Why is Record at a different version? Are all packages at the correct version?

@thedavidprice hum that's a mistake indeed - it's a preproduction branch and I had a branch for RW version bump and one which introduced RW records, both were not at the same version indeed.

Nevertheless, I recreated the preproduction branch from main and only merged the version bump branch.
I then:
- removed yarn.lock
- ran `yarn dedupe`
- adapted the workflow according to the steps found in the smoke tests, to have a file as such:
```
on:
  push:
    branches:
      - preprod

name: Deploy preprod

env:
  repo_name: ***
  node_version: 16.6.1

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: preproduction

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.6.1

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Cache yarn
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-1234-${{ hashFiles('yarn.lock') }} #change yarn-{randomString} to bust the cache
          restore-keys: |
            yarn-1234

      - name: Create environment files
        working-directory: aws
        run: |
          yarn install --immutable
```

Which introduces the `yarn install --immutable`.

I still get the same error though.

@virtuoushub is it something you have resolved in those projects?
