### ISSUE TITLE
[Testing] Get Jest up and running

### ISSUE THREAD

**Issue by RobertBroersma** [redwoodjs/redwood#502]
As discussed [on the forum](https://community.redwoodjs.com/t/testing-in-redwood/482/6)

## Goal
To be able to succesfully run `yarn rw test` after creating a new app and generating new components.

## Steps
- [x] Create Jest Config for **web**
- [x] Configure `@redwoodjs/router` Routes to work inside tests.
- [ ] Create Jest Config for **api**

> We already have a bunch of jest related config files over here: https://github.com/redwoodjs/redwood/tree/master/packages/core/config

**Comment by thedavidprice** [comment]
Related topic --> adding here so it doesn't get lost.

From #181, how do we want to handle:
> if additional config is needed, capability for simple config extension managed from either App root or specific to App sides (e.g. web/, api/, etc.).

**Comment by RobertBroersma** [comment]
I'm looking into the API side of testing. I think the best would be to have a database or a mocked database somehow, and let tests just run the services and assert on said database (through the prisma client perhaps?)

As I mentioned in [this topic](https://community.redwoodjs.com/t/testing-in-redwood/482) I think an in-memory SQLite database would be very easy for this.

However as @olance also mentioned in that topic: databases are different, you can't just swap out a Postgres databse for an in-memory SQLite database.

However if we're thinking of Redwood as the ideal future, we could argue that it's Prisma's job to deal with the database, and we don't care about which database is used, we're only interfacing with the Prisma client.

I see 2 options:
1. We _somehow_ spin up a postgres instance for the tests. ([See this repo for example](https://github.com/ctrlplusb/prisma-pg-jest)). This sounds slow to me, but I haven't tried it yet.
2. In-memory database using SQLite. This is currently [not implemented in Prisma](https://github.com/prisma/prisma/issues/732), but I suppose we could help out there if this is feasible.

Other things:
There's [a dedicated package by the Prisma team](https://github.com/prisma/prisma-test-utils), which is currently umaintained, but could be promising in the future. It uses the method of spinning up a database. Perhaps we could continue a fork, or contribute to that package? Or wait?

Let me know what you think or if any or none of that makes sense! @thedavidprice @olance @peterp

**Comment by olance** [comment]
> However if we're thinking of Redwood as the ideal future, we could argue that it's Prisma's job to deal with the database, and we don't care about which database is used, we're only interfacing with the Prisma client.

If by this you mean: we leave the DB choice to the user and don't try to interfere because it's Prisma's responsibility, then I agree.
If however you mean: we want to use SQLite and we shouldn't have to care because Prisma will adapt to whatever DB is being used, then I don't 😅 

And actually, I don't think it's a matter of agreeing or not: there's a wide range of features that exist on Postgres that do not on SQLite (thinking about enums for instance, but there's probably more). And Prisma will for sure adapt from one to another when features exist on both sides, but it cannot make up for missing features between the two systems.

Coming from Rails, I see a third options: it's the responsibility of the developer to spin up their own DB. I think trying to be smarter than this would come at a price on flexibility, putting unnecessary constraints on the developer's setup.

The way Rails does this, is by having a configuration file for DB credentials, such as:

```yaml
development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: db_dev
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: db_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
```

I fill in the information depending on my own setup, and things are ready to roll!
I really don't think it's asking too much to require the devs to have their own db running when they want to use something else than SQLite.
