### ISSUE TITLE
Add before/after lifecycle hooks to Baremetal deploy

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#5297]
This gives the ability to run arbitrary code before/after any of the existing steps: update, install, migrate, build, restart.

Global before/after hooks that apply to all servers in all environments:

```toml
[[servers.production]]
host = "server.com"
# ...

[before]
install = ["yarn clean"]

[after]
install = ["cp -R * backup"]
```

If you want some per enviroment:

```toml
[before.staging]
install = ["yarn clean"]

[before.production]
install = ["cp -R * backup"]
```

Or you can have some on a per-server basis:

```toml
[[servers.production]]
host = "server.com"
before.install = "yarn clean"
```

These configurations will stack and execute them in the following order:

1. Global
2. Per environment
3. Per server

So in the most complex example:

```toml
[[servers.production]]
host = "server.com"
before.install = "echo 'server'"

[before]
install = ["echo 'global'"]

[before.production]
install = "echo 'environment'"
```

You would see the following output:

```bash
global
environment
server
```

The actual commands to be run can be a string or an array of strings if you want to run multiple commands:

```toml
[before.production]
install = ["yarn clean", "rm -rf log/*"]
```
