### ISSUE TITLE
[Bug?]: dbAuth - getToken response is empty with serverless deploy

### ISSUE THREAD

**Issue by philippefuentes** [redwoodjs/redwood#5871]
### What's not working?

Hi all, 
Having problems making dbAuth work on AWS using serverless deploy:

The response cookie returned by `auth` is ok the the one returned by `getToken` is empty.

The web domain is `facturation.mydomain.com` and api domain is the AWS API Gateway form `xxxxxx.execute-api.eu-west-1.amazonaws.com` 

Here are details about the `auth` request:

![auth-headers](https://user-images.githubusercontent.com/18396482/177111471-f54b31a3-590a-4b2a-8c8c-6f159b303509.png)

![auth-cookie](https://user-images.githubusercontent.com/18396482/177110830-2032a3ad-e27a-4594-87c4-133dd28201cd.png)

Here are details about the `getToken` request:

![getToken-headers](https://user-images.githubusercontent.com/18396482/177110894-65af110f-860c-40c6-8ee0-17212f8aab1b.png)

![getToken-cookie](https://user-images.githubusercontent.com/18396482/177110912-e982803d-3be7-4470-855a-ef599a56cd07.png)

My serverless.yml is as follow (based on `yarn rw setup deploy serverless`), with CORS setup:

```
...
provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1 # AWS region where the service will be deployed, defaults to N. Virginia
  httpApi:          # HTTP API is used by default. To learn about the available options in API Gateway, see https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-vs-rest.html
    cors:
      allowedOrigins:
        - '*' # This is the default value. You can remove this line if you want to restrict the CORS to a specific origin.
      # allowCredentials: true # allowCredentials should only be used when allowedOrigins doesn't include '*'
      allowedHeaders:
        - authorization
        - auth-provider
        - content-type
        - X-Amz-Date
        - X-Api-Key
        - X-Amz-Security-Token
        - X-Amz-User-Agent
    payload: '1.0'
    useProviderTags: true # https://www.serverless.com/framework/docs/deprecations/#AWS_HTTP_API_USE_PROVIDER_TAGS
...
```

### What's your environment? (If it applies)

```shell
System:
    OS: Linux 5.13 Ubuntu 20.04.4 LTS (Focal Fossa)
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.15.1 - /tmp/xfs-dc904f89/node
    Yarn: 3.2.0 - /tmp/xfs-dc904f89/yarn
  Databases:
    SQLite: 3.31.1 - /usr/bin/sqlite3
  Browsers:
    Chrome: 103.0.5060.53
    Firefox: 101.0.1
  npmPackages:
    @redwoodjs/core: ^2.0.0 => 2.0.0
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by eussam** [comment]
My web inspector does not show any error related to CORS, as I understand that the following lines in the serverless.yml file allow me to accept any origin:
```

cors:
      allowedOrigins:
        - '*'
```
What am I understanding wrong then ?

**Comment by rayelward** [comment]
I was dealing with this same exact issue a couple weeks ago. The reason the getToken call has an empty session cookie is because there is no request cookie header sent on that request. To allow that cookie to carry over, from the auth POST call, the browser needs "allowCredentials" to be true and "allowedOrigins" to be specific domains the browser is making the calls from.

I was just trying to say the redwood cors guide (https://redwoodjs.com/docs/cors) gets you there with all the details and code changes needed. The guide just doesn't specify the needs of a serverless AWS deployment where the domain and allow credentials needs to be manually updated in the serverless.yml as well.

**Comment by eussam** [comment]
Ok, thank you for your time.
I followed the guide you mentioned and had to indeed update the serverless.yml as well as follows:
```
cors:
      allowedOrigins:
        - 'https://facturation.mydomain.com' 
      allowCredentials: true
```

Everything works as expected now.
