### ISSUE TITLE
[Bug?]: Published @redwoodjs/forms does not have correct dependencies

### ISSUE THREAD

**Issue by dphuang2** [redwoodjs/redwood#6373]
### What's not working?

It seems like `@redwoodjs/forms@2.2.4` has `react-hook-form@7.33.1` in its `package.json` but it should be `7.34.2`: https://github.com/redwoodjs/redwood/blob/main/packages/forms/package.json

Is there something up with the publishing of `@redwoodjs/forms` that causes this?

See SS of `node_modules` source for `@redwoodjs/forms`
<img width="966" alt="Screen Shot 2022-09-09 at 5 09 53 PM" src="https://user-images.githubusercontent.com/14287381/189460709-732ba65a-0c73-455d-8c3c-6840f7be20a5.png">

### How do we reproduce the bug?

Simply install the latest `redwoodjs` and observer that `yarn.lock` has:

```
"react-hook-form@npm:7.33.1":
  version: 7.33.1
  resolution: "react-hook-form@npm:7.33.1"
  peerDependencies:
    react: ^16.8.0 || ^17 || ^18
  checksum: 6380700d877604be4326c845599240a42bb4eb31109ff47cd6aa9e567a906c9fe512c965396a72c6a0e52a4992922226ea58cf8bfb43d6ebbaa08972e8be4c65
  languageName: node
  linkType: hard
```

### Are you interested in working on this?

- [ ] I'm interested in working on this
