### ISSUE TITLE
[Bug?]: Storybook not generating when there's a custom @font-face

### ISSUE THREAD

**Issue by ahaywood** [redwoodjs/redwood#9108]
### What's not working?

Storybook is erroring out if there's a custom `@font-face` block within my index.css

<img width="1217" alt="CleanShot 2023-08-31 at 13 19 05@2x" src="https://github.com/redwoodjs/redwood/assets/212300/cd55976c-8ad8-4b29-908f-4b4b1fc0f061">

Here's a Loom video demonstrating:
https://www.loom.com/share/d75b96e132cc44219bb44fa503d5dd73

My fonts are within a `public/fonts` directory, which is [aligned with the documentation.](https://redwoodjs.com/docs/assets-and-files#custom-fonts)

A few notes:
- I am using Tailwind. I haven't tried replicating without Tailwind
- In the Loom video, I'm using this repo: https://github.com/ahaywood/redwoodjs-partner-badges but I have been able to replicate the problem within a fresh install

### How do we reproduce the bug?

```
yarn create redwood-app my-redwood-project
cd my-redwood-project
yarn install
yarn rw setup ui tailwindcss
```

- Add a custom font to `public/fonts`
- Within index.css, add a custom `@font-face` block. (Here's mine):

```
@font-face {
  font-family: "Eagle Sight";
  src: url("/fonts/eagleSight/EagleSightRegular.ttf") format("truetype"),
    url("/fonts/eagleSight/eaglesightregular-webfont.woff") format("woff"),
    url("/fonts/eagleSight/eaglesightregular-webfont.woff2") format("woff2");
}

/* sherman */
@font-face {
  font-family: "Sherman";
  src: url("/fonts/sherman/Sherman-Display.woff") format("woff"),
    url("/fonts/sherman/Sherman-Display.woff2") format("woff2");
}
```

Run `yarn rw storybook`

Everything seems to be running fine in dev `yarn rw dev`

### What's your environment? (If it applies)

```shell
System:
    OS: macOS 13.3
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.3.0 - /private/var/folders/f4/q5j7cnt15hvftx0cp3w8h8nr0000gn/T/xfs-3121f286/node
    Yarn: 3.6.1 - /private/var/folders/f4/q5j7cnt15hvftx0cp3w8h8nr0000gn/T/xfs-3121f286/yarn
  Databases:
    SQLite: 3.39.5 - /usr/bin/sqlite3
  Browsers:
    Chrome: 116.0.5845.140
    Edge: 116.0.1938.62
    Safari: 16.4
  npmPackages:
    @redwoodjs/auth-dbauth-setup: 6.1.0 => 6.1.0 
    @redwoodjs/cli-storybook: 6.1.0 => 6.1.0 
    @redwoodjs/core: 6.1.0 => 6.1.0
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by rkmitra1** [comment]
Get the same error (but due to markdown file)
![Screenshot 2023-08-31 at 6 40 00 PM](https://github.com/redwoodjs/redwood/assets/69916391/abdc21fb-2bbf-46ce-850a-d05401b37dc0)

### I have narrowed down my problem to loading a markdown file in my component.

import helpContent from './Help.md?raw'

This works in the normal dev server, not storybook.

if  I comment out that line and replace with 

const helpContent = `test`

it works

Does Storybook still use webpack? if so, does the loader need to be configured.

**Comment by rkmitra1** [comment]
Update to my previous comment. Note: my problem is with loading a markdown file (but I believe the fonts issue is similar)

As suspected my storybook is still using webpack (even though my project is vite). Redwood version 6.1.0

My fix (workaround)

1. Setup additional webpack configuration
  - yarn rw setup webpack
2. edit the created web/config/webpack.config.js file
  - add a rule for markdown files
  - I have attached my file 
<img width="602" alt="image" src="https://github.com/redwoodjs/redwood/assets/69916391/7a5f171c-23f3-4614-be0a-e8be55fb08e4">

3. In my case, I also had to add the raw-loader package
  - yarn add raw-loader


EXTRA CREDIT
I found the redwood stats functionality command that I had not used before. Might be useful to track down webpack issues and easily determine if your new configuration is working.

yarn rw build --stats

**Comment by jtoar** [comment]
I recently looked at this and at least for Amy's cause, it seems like it's because of new lines in the properties using the `url` function:

```css
@font-face {
  font-family: "My font";
  /* 👇 The new lines here may cause an error */
  src: url("/fonts/myFont/MyFont.ttf") format("truetype"),
    url("/fonts/myFont/myfontbold.woff") format("woff"),
    url("/fonts/myFont/myfontregular.woff2") format("woff2");
}
```

When I got rid of those new lines, the error went away:

```css
@font-face {
  font-family: "My font";
  src: url("/fonts/myFont/MyFont.ttf") format("truetype"), url("/fonts/myFont/myfontbold.woff") format("woff"), url("/fonts/myFont/myfontregular.woff2") format("woff2");
}
```

So, there's one possible workaround.
